[package]
name = "rust-webpki-harness"
version = "0.1.0"
edition = "2021"

[dependencies]
limbo-harness-support = { path = "../../harness-support/rust" }
chrono = "0.4.42"
pem = "3.0.6"
serde_json = "1.0.148"
webpki = { version = "0.22.4", features = ["std"] }
