[package]
name = "rust-rustls-harness"
version = "0.1.0"
edition = "2021"

[dependencies]
limbo-harness-support = { path = "../../harness-support/rust" }
chrono = "0.4.38"
pem = "3.0.4"
serde_json = "1.0.124"
rustls-webpki = { version = "0.102.6", features = ["std"] }
